### ISSUE TITLE
Issue Installing ZNC on Centos 6 64-BIT

### ISSUE THREAD

**Issue by fahadmehar** [jlinoff/gcc-4.9.1-boost-1.55#1]
configure: No compiler with C++11 support was found
configure: error: Upgrade your compiler. GCC 4.7+ and Clang 3.2+ are known to work.

And Also I have IDENT problem... I am getting this (~) on my IDENT.

**Comment by jlinoff** [comment]
When you run `yum info gcc` on your host what do you see?

**Comment by fahadmehar** [comment]
Mine is Debian not Centos.

**Comment by jlinoff** [comment]
Sorry about that, what is the output of `apt-get info gcc`?

**Comment by fahadmehar** [comment]
Actually i change my OS so in debian "apt-get info gcc" command is not working.

**Comment by jlinoff** [comment]
Are still having problems since you changed to a new OS? If so, what is the output of `gcc --version`?

**Comment by fahadmehar** [comment]
Actually yes... My OS is Debian 8.7 Jesse 64 BIT... and I got this error 
wrong ELF class: ELFCLASS32....  I need to fix this error...

**Comment by jlinoff** [comment]
Where did this error come from? Is it from the script? If so, can you provide some context?

**Comment by fahadmehar** [comment]
And even I can't able to connect throw cuteFTP - 

ERROR:>   	[1/31/2017 8:56:18 PM] Disconnect: key exchange failed.
ERROR:>   	[1/31/2017 8:56:18 PM] Check security settings; make sure that the username and password are correct, and that the chosen encryption algorithms are supported by server.

**Comment by fahadmehar** [comment]
Can't load modules gseen: /home/Statistics/eggdrop/modules/gseen.so: wrong ELF class: ELFCLASS32

When I try to Install Gseen and Stats on my eggdrop.

**Comment by fahadmehar** [comment]
Can't load modules gseen: /home/Statistics/eggdrop/modules/gseen.so: wrong ELF class: ELFCLASS32

When I try to Install Gseen and Stats on my eggdrop.

**Comment by jlinoff** [comment]
It sounds like your system is an unusable state. This script will not work until that is addressed.

**Comment by jlinoff** [comment]
Is it okay if I close this issue or would you prefer that i wait until your system is stable and you have tried again?

**Comment by fahadmehar** [comment]
I have show you the error now. If you have solution tell me

**Comment by jlinoff** [comment]
Ok, please show me the error.

As a side note, you mentioned that you are running Debian 6 (squeeze), that is pretty old according to: https://www.debian.org/releases/. You might want to consider upgrading to Debian 8 (Jessie) if that is possible.

**Comment by fahadmehar** [comment]
I am using Debian 8 jessie new version

**Comment by fahadmehar** [comment]
wrong ELF class: ELFCLASS32 this is the error

**Comment by jlinoff** [comment]
I am sorry, what does this have to do with the gcc installation script? I don't even know what ZNC is.

**Comment by fahadmehar** [comment]
Man,,, I am asking you about this error which i think i have shown you more then 4 times. Why this error occurs ? forget about ZNC I am not talking about ZNC

**Comment by jlinoff** [comment]
I can understand that this may be frustrating for you but you have sent me an error message with no context. i have no idea what the error message relates to and have not seen it before so I do not know how to help you.

Could you send me the command that you ran and the output of that command? That might provide sufficient context to move things forward.

**Comment by jlinoff** [comment]
Also, please note that the title of this issue is *Issue Installing ZNC on Centos 6 64-BIT* which is why i thought that you were referring to ZNC.

**Comment by fahadmehar** [comment]
Oh i see. Ok thanks.

**Comment by fahadmehar** [comment]
When i have problem in installing znc i will let you know
